baseURL = ""
languageCode = "en"
DefaultContentLanguage = "it"
title = "Personal Website"
theme = "anatole"
summarylength = 100
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "G-QNK934C7WZ"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Valentina Saccucci"
author = "Valentina Saccucci"
#copyright = "2020-2021"
description = "Personal Website"
profilePicture = "images/profile1.jpg"
keywords = ""
favicon = "fav/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = [""]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
# indexDateFormat = "Mon, Jan 2, 2006"
# listDateFormat = "Jan 2"
# singleDateFormat = "Mon, Jan 2, 2006"

[params.simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:valentinasaccucci999@gmail.com"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/valentinasaccucci/?hl=it"

[[params.socialIcons]]
icon = "fab fa-facebook"
title = "facebook"
url = "https://www.facebook.com/valentinasaccucci99/"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/valentina-saccucci-497465177/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/ValeSac"


## Menu items

#[menu]
  #[[menu.main]]
  #name = "About me"
  #identifier = "home"
  #weight = 100
  #url = "/"

  #[[menu.main]]
  #name = "About Me"
  #weight = 200
  #identifier = "about"
  #url = "/about/"

  #[[menu.main]]
  #name = "Posts"
  #weight = 300
  #identifier = "posts"
  #url = "/post/"
